spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/redis_test
    username: root
    password: zkfxhlrkr
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 9000